name = "nemo-password-manager"
compatibility_date = "2024-04-07"

[[d1_databases]]
binding = "DB"
database_name = "nemo-password-manager"
database_id = "your-d1-id"

[vars]
API_ACCESS_KEY = "super-secret-key"
